#!/bin/bash

rm -rf ./out

source ./env-$USER

cat sample.csv | \
    go run src/pass2pass/cmd/pass2pass.go \
        -parser lastpass \
        -store plain \
        -field-cleaner-group './templates/util/field-clean-group' \
        -field-cleaner-name './templates/util/field-clean-name' \
        -path-filter './templates/util/path-filter' \
        -path-replacer './templates/util/path-replace' \
        "./templates/multiline-scheme" \
        "./out"

#cat sample.csv | \
#    go run src/pass2pass/cmd/pass2pass.go \
#        -parser lastpass \
#        -store plain \
#        -field-cleaner-group './scriptlets/cmd-path-clean.sh' \
#        -field-cleaner-name './scriptlets/cmd-path-clean.sh' \
#        -path-filter './scriptlets/cmd-path-filter.sh' \
#        -path-replacer './scriptlets/cmd-path-replace.sh' \
#        "./templates/dir-scheme" \
#        "./out"

#cat sample.csv | \
#    go run src/pass2pass/cmd/pass2pass.go \
#        -parser lastpass \
#        -store cmd \
#        -field-cleaner-group './scriptlets/cmd-path-clean.sh' \
#        -field-cleaner-name './scriptlets/cmd-path-clean.sh' \
#        -path-filter './scriptlets/cmd-path-filter.sh' \
#        -path-replacer './scriptlets/cmd-path-replace.sh' \
#        "./templates/dir-scheme" \
#        './scriptlets/cmd-plain.sh'

#cat sample.csv | \
#    go run src/pass2pass/cmd/pass2pass.go \
#        -parser lastpass \
#        -store cmd \
#        -field-cleaner-group './scriptlets/cmd-path-clean.sh' \
#        -field-cleaner-name './scriptlets/cmd-path-clean.sh' \
#        -path-filter './scriptlets/cmd-path-filter.sh' \
#        -path-replacer './scriptlets/cmd-path-replace.sh' \
#        "./templates/multiline-scheme" \
#        './scriptlets/cmd-plain.sh'

#cat sample.csv | \
#    go run src/pass2pass/cmd/pass2pass.go \
#        -parser lastpass \
#        -store cmd \
#        -field-cleaner-group './templates/util/field-clean-group' \
#        -field-cleaner-name './templates/util/field-clean-name' \
#        -path-filter './templates/util/path-filter' \
#        -path-replacer './templates/util/path-replace' \
#        "./templates/multiline-scheme" \
#        './scriptlets/cmd-pass.sh'
