#!/bin/bash

rm -rf ./out

source ./env-$USER

#cat sample.csv | \
#    go run src/pass2pass/cmd/pass2pass.go \
#        -parser lastpass \
#        -store plain \
#        -path-cleaner './cmd-path-clean.sh' \
#        -path-filter './cmd-path-filter.sh' \
#        -path-replacer './cmd-path-replace.sh' \
#        "./templates/dir-scheme" \
#        "./out"

#cat sample.csv | \
#    go run src/pass2pass/cmd/pass2pass.go \
#        -parser lastpass \
#        -store cmd \
#        -path-cleaner './cmd-path-clean.sh' \
#        -path-filter './cmd-path-filter.sh' \
#        -path-replacer './cmd-path-replace.sh' \
#        "./templates/dir-scheme" \
#        './cmd-plain.sh'

#cat sample.csv | \
#    go run src/pass2pass/cmd/pass2pass.go \
#        -parser lastpass \
#        -store cmd \
#        -path-cleaner './cmd-path-clean.sh' \
#        -path-filter './cmd-path-filter.sh' \
#        -path-replacer './cmd-path-replace.sh' \
#        "./templates/multiline-scheme" \
#        './cmd-plain.sh'

cat sample.csv | \
    go run src/pass2pass/cmd/pass2pass.go \
        -parser lastpass \
        -store cmd \
        -path-cleaner './cmd-path-clean.sh' \
        -path-filter './cmd-path-filter.sh' \
        -path-replacer './cmd-path-replace.sh' \
        "./templates/dir-scheme" \
        './cmd-pass.sh'
